# Generated by Django 3.1.7 on 2021-03-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='Ваше имя:')),
                ('data', models.TextField(verbose_name='Поле для ответа:')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта для обратной связи:')),
            ],
        ),
    ]
