# Generated by Django 3.1.7 on 2021-03-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=64, verbose_name='Название книги')),
                ('full_name', models.CharField(max_length=64, verbose_name='Имя Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта для подтверждения')),
            ],
        ),
    ]
