# Generated by Django 3.1.7 on 2021-03-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bookmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='county',
            new_name='country',
        ),
    ]
