# Generated by Django 3.1.7 on 2021-03-12 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210306_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsHistoryModel',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.bookmodel')),
                ('full_name', models.CharField(max_length=64, verbose_name='Имя Фамилия')),
                ('date_of_issue', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата выдачи')),
                ('return_date', models.DateTimeField(blank=True, verbose_name='Дата возврата')),
            ],
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='amount_in_stock',
            field=models.IntegerField(verbose_name='Имеющееся количество'),
        ),
    ]
