# Generated by Django 3.1.7 on 2021-03-12 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210312_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientshistorymodel',
            name='date_of_issue',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='clientshistorymodel',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
